package universite_paris8.iut.kkr.zelda.modele;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import universite_paris8.iut.kkr.zelda.Utils.ConstantesTuile;

public class Environnement {

	private int largeur, hauteur;
	private ObservableList<Acteur> acteurs;
	private IntegerProperty nbToursProperty;

	private int[][] tableauMap = {
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, 2, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, 2, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, 2, ConstantesTuile.HERBE, ConstantesTuile.HERBE, 3, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, 4, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.EAU},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
			{ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.EAU, ConstantesTuile.EAU, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE, ConstantesTuile.HERBE},
	};

	public Environnement(int largeur, int hauteur) {
		super();
		this.largeur = largeur;
		this.hauteur = hauteur;
		this.nbToursProperty = new SimpleIntegerProperty(ConstantesTuile.EAU);
		this.acteurs = FXCollections.observableArrayList();
	}

	public int[][] getTableauMap() {
		return this.tableauMap;
	}


	public ObservableList<Acteur> getActeurs() {
		return acteurs;
	}

	public Acteur getActeur(String id) {
		for (Acteur a : this.acteurs) {
			if (a.getId().equals(id)) {
				return a;
			}
		}
		return null;
	}

	public void ajouter(Acteur a) {
		acteurs.add(a);
	}

	public int getTileId(int x, int y) {
		int colonneGrille = (x+6)  / 30; // Calculer l'indice de la colonne de la grille correspondant à la position x
		int ligneGrille = (y+19) / 30; // Calculer l'indice de la ligne de la grille correspondant à la position y
		return tableauMap[ligneGrille][colonneGrille];
	}

	public boolean estPositionValide(int x, int y) {
		return Collision.position(x, y, largeur, hauteur, tableauMap);
	}




	//methode trouver ennemi proche public Ennemi trouverEnnemiProche(int x, int y, int portee) {
	//        for (Ennemi ennemi : ennemis) {

}
